import tkinter as tk
testing = tk.Tk()
frame = testing.geometry("500x500")
testing.title("Account Login + SignUp")
tk.Label(text="Welcome to NullEscape Arcade! Choose Login Or Register", bg="light slate blue", width="500", height="3", justify = "left",font=("Helvetica", 18)).pack()
tk.Label(text="Choose Login to sign in Or Register to create an account", bg="white", width="500", height="2", font=("Helvetica", 16)).pack()
tk.Label(text="Enter Username", bg="white", width="500", height="2", font=("Helvetica", 16)).pack()
tk.Entry(testing).pack()
tk.Label(text="Enter Password", bg="white", width="500", height="2", font=("Helvetica", 16)).pack()
tk.Entry(testing).pack()
loginbutton = tk.Button(text="Login",fg = "red", height="2", width="20")
loginbutton.pack()
signupbutton = tk.Button(text="Sign Up",fg = "red", height="2", width="20")
signupbutton.pack()
testing.mainloop()
